### ISSUE TITLE
Home Notifications

### ISSUE THREAD

**Issue by rbyrbt** [luisiam/homebridge-foscamcamera#10]
Running the latest 0.1.18 with multiple Foscam R2 streams and they are all looking great. Small notification issue however - Home Notification Thumbnails appear to be inconsistent. Meaning, a motion notification will trigger for one camera ex: Cam 1, but the camera notification and notification thumbnail may come from a different camera (Cam 2, 3, etc).

**Comment by rbyrbt** [comment]
A little more info, actually I'm not seeing any consistency with the notification sensor label ("Cam1 Motion Detected") and the camera thumbnail. What I am seeing however, is that the first camera in the config file appears to be the destination when following any of the Home notifications?

**Comment by luisiam** [comment]
When motion is detected, can you see corresponding camera `Getting snapshot` and `Got snapshot` from the log?

For me, the notification snapshot is hit and miss. However, the log shows that the correct camera is getting the snapshot every time. I believe this issue has to do with the HomeKit notification system itself.

**Comment by rbyrbt** [comment]
Yes the log looks correct, but the snapshot is all over the place. Were you able to replicate following the Home notification going to the first camera's stream? Meaning (snapshot mismatch aside) the notification would correctly be from Cam 2 or 3, but on 3D-touch, the notification brings up the Cam 1 stream?

Just installed 0.2.0 with a lower motion sensitivity so this should help to get a better handle on the notifications. Thanks.

**Comment by luisiam** [comment]
On my setup, notification always bring me to the correct stream. Sometimes it will fail to start the stream though. In terms of snapshots, sometimes the notification doesn't even show a snapshot.

**Comment by luisiam** [comment]
What does the log say when you bring up the stream from notification? Does it always point to the same camera?

**Comment by rbyrbt** [comment]
Just upgraded to 0.2.2, and removed/re-added all my cameras back to HomeKit. I think things are working consistently now. The correct stream is coming up when following the notification (and the log mirrors this) - So I think I'm good. Will keep an eye on it for the next few days. Appreciate it. Thanks!
