### ISSUE TITLE
Foscam plugin and iOS 10.1+

### ISSUE THREAD

**Issue by naixra** [luisiam/homebridge-foscamcamera#14]
Hello,

since last iOS update, Foscam plugin doesn't work well with Home App. Indeed, I can add the camera has Homebridge, then get the motion detector and camera in the application home. But since the update, I do not seem to get the viewing of the live camera. The preview starts well a day when I quit and relaunch the application (with the time displayed on the picture, I see that it starts to-date), but whenever I click to see the video it makes me be a message that the application Home can not connect to the camera, or I see a still image (time not advance) and a countdown since the last refresh image. Whereas before I could watch the live camera from the Home application.

Thank you.

**Comment by Kinzal16** [comment]
Hello, the problem I have also in the "Home" app. You can not see a live picture.

In other HomeKit apps, the live image does not work.

And you can not control the microphone and speakers from the camera via a HomeKit apps. 
It would be very nice if it worked soon in a new version of Foscam plugin. Thank you

**Comment by luisiam** [comment]
Do you have any homebridge log regrading that issue? Mine still works fine after the update. Thanks.

**Comment by naixra** [comment]
I get this in log. Do you think it is because of this that there is this issue?

'2016-10-25 01:02:00] [Foscam R2] Foscam-NG: Got snapshot.
oct. 25 01:02:00 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:00] [Foscam R2] Foscam-NG: Got snapshot.
oct. 25 01:02:00 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:00] [Foscam R2] Foscam-NG: Got snapshot.
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:09] [Foscam R2] { message: 'Keepalive failed',
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]:   code: 1,
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]:   data: <Buffer@0x2d114b8 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00> }
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:09] [Foscam R2] Resetting connection to server...
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:09] [Foscam R2] Connected to server for motion notification.
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:09] [Foscam R2] { message: 'Keepalive failed',
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]:   code: 1,
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]:   data: <Buffer@0x2d114b8 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00> }
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:09] [Foscam R2] Resetting connection to server...
oct. 25 01:02:09 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:09] [Foscam R2] Connected to server for motion notification.
oct. 25 01:02:10 medianucenter-desktop homebridge[9240]: (node:9240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): [object Object]
oct. 25 01:02:14 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:14] [Foscam R2] Foscam-NG: Getting snapshot.
oct. 25 01:02:15 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:15] [Foscam R2] Foscam-NG: Got snapshot.
oct. 25 01:02:27 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:27] [Foscam R2] Foscam-NG: Getting snapshot.
oct. 25 01:02:27 medianucenter-desktop homebridge[9240]: [2016-10-25 01:02:27] [Foscam R2] Foscam-NG: Got snapshot.´

I can't get live video anymore on Home App, the picture refresh every 10 seconds but I can't get any live video.

Thanks.

**Comment by luisiam** [comment]
Can you run homebridge with `DEBUG=*` and post the full log? From what I can see on your log, you are not requesting a stream. Do you mean you cannot get live streaming in the "overview" section? The "overview" section of the Home app is never streaming from the camera, it only provide snapshots. You have to click on the snapshot and the streaming starts after the video goes full screen.

**Comment by Samfox2** [comment]
I'm getting the same error with a C2: "keepallive failed"

**Comment by naixra** [comment]
Hello,

Yes, the "overview" section Home app provide snapshots, however, before when I click on the snapshot I get a streaming video. Now, when I click I get a error (it says "App doesn't able to connect camera") or a snapshot with a countdown since the last refresh image (snapshot refresh every 10 secondes), not a streaming video like before.

I use homebridge as a service with systemctl and I flag config.json file in other home folder, I can't use DEBUG=\* homebridge command, it starts with a "new" configuration for my real config.json file is in /var/homebridge/ and persist folder too.

How can I get full debug file with systemctl? I can only show journalctl.

Thanks.

**Comment by luisiam** [comment]
I can duplicate the issue after I updated my AppleTV. We are currently troubleshooting the issue.

**Comment by Samfox2** [comment]
Great, thx

**Comment by CharlyFive** [comment]
Please fix it

**Comment by TheRoolBool** [comment]
In iOS 10.2, the live view is working again

**Comment by CharlyFive** [comment]
With iOS 10.2 (Beta 1), the live view is working again

**Comment by johnx102** [comment]
I just update my iPhone to 10.2 beta 3 , same issue with 2 installation, 1 with Foscam C1, the other with Foscam f9831W V2. Just censor and snapshot working, but still no live view ;(

**Comment by CharlyFive** [comment]
Funny, with me the live view with iOS 10.2 current beta

**Comment by johnx102** [comment]
You do somerhîg spécial for or work ? The log seem to b good , i CAN stream the Camera directly on rtsp witz vlc , but no live view un ios home ....

**Comment by CharlyFive** [comment]
I have done nothing.

**Comment by johnx102** [comment]
Ok thank's for answer , it's wird... you have foscam c1 model ?

**Comment by CharlyFive** [comment]
FI9831P V2

**Comment by johnx102** [comment]
Ok thanks

**Comment by johnx102** [comment]
i don't know how i can solve this ....
where can i see in the log home bridge if there is problem with rtsp stream ?

**Comment by johnx102** [comment]
LE problème vient peut être de la ... quand je lance en début, voici les messages..



StreamController Client claims it doesn't support SRTP. The stream may stops working with future iOS releases. +253ms
  StreamController Client claims it doesn't support SRTP. The stream may stops working with future iOS releases. +64ms
  StreamController Client claims it doesn't support SRTP. The stream may stops working with future iOS releases. +17ms
  StreamController Client claims it doesn't support SRTP. The stream may stops working with future iOS releases. +11ms
[11/21/2016, 12:41:32 PM] [Foscam C1] Connected to server for motion notification.
  EventedHTTPServer Server listening on port 45693 +788ms
[11/21/2016, 12:41:32 PM] Foscam C1 is running on port 45693.
  rtsp-stream start-line sent OPTIONS rtsp://192.168.3.71:554/videoMain RTSP/1.0 +8s
  rtsp-stream headers sent { CSeq: 1, 'User-Agent': 'homebridge-foscam-stream/0.3.7' } +4ms
  rtsp-stream start-line sent OPTIONS rtsp://192.168.3.71:554/videoMain RTSP/1.0 +17ms
  rtsp-stream headers sent { CSeq: 1, 'User-Agent': 'homebridge-foscam-stream/0.3.7' } +1ms
  rtsp-stream start-line sent OPTIONS rtsp://192.168.3.71:554/videoSub RTSP/1.0 +5ms
  rtsp-stream headers sent { CSeq: 1, 'User-Agent': 'homebridge-foscam-stream/0.3.7' } +1ms
  rtsp-stream start-line sent OPTIONS rtsp://192.168.3.71:554/videoSub RTSP/1.0 +7ms
  rtsp-stream headers sent { CSeq: 1, 'User-Agent': 'homebridge-foscam-stream/0.3.7' } +1ms

**Comment by johnx102** [comment]
i think my problem is this ...
maybe someone can help me 
 rtsp-stream decoding chunk 'RTSP/1.0 401 Unauthorized\r\nServer: Hisilicon Streaming Media Server/1.0.0

**Comment by luisiam** [comment]
From iOS 10.1, SRTP is enforced which is not used in the current streaming library. Since I am not the one who develops the streaming library, I am still waiting for the library developer to fix it.

**Comment by johnx102** [comment]
Ok thanks

**Comment by naixra** [comment]
Hello,

iOS 10.2 final is out, any news about live view in Home App?

Thank you.

**Comment by luisiam** [comment]
Doesn't seem to work yet

**Comment by rbyrbt** [comment]
I've intentionally kept my AppleTV on tvOS 10.0 and live-view streaming appears to be working fine to iOS 10.2 (R2 & C2 cameras) when accessing remotely. I imagine this is because tvOS 10.0 does not enforce SRTP. When on the local network, live view hasn't worked since iOS 10.1 when SRTP was introduced. Anyway, nothing which hasn't already been discussed, but just a little info that may help. Keep up the great work, hopefully we'll get a streaming library update soon - thanks.

**Comment by ctaloi** [comment]
Such a slick use of Foscam in HomeKit, hope this is a challenge we can overcome. Reading this, the video stream needs to be srtp, correct?  And currently the lib used to handle the video does not support srtp and it seems the dev isn't adding it (based on lack of updates to repo).

**Comment by ctaloi** [comment]
Live video is back in iOS 10.3 beta !

**Comment by LevelOne2k** [comment]
For me it does not work with iOS 10.3

**Comment by ctaloi** [comment]
It's working when on my LAN on an iPhone and Apple Watch. It does not work across the WAN when the Apple TV acts as the hub ( but I have not yet upgraded the Apple TV ). 

---
Christopher Aloi

**Comment by johnx102** [comment]
Yes same for me, working on lan but not from external, i use ipad Like hub ios10.3beta1

**Comment by marcodesantis71** [comment]
Yes. I confirm with my C2 works fine.
But with my FI9816P does not work streaming

**Comment by Lestercity** [comment]
So C2 works fine. Anyone has it working remotely through apple tv hub?

**Comment by LevelOne2k** [comment]
I removed the camera from HomeKit and added again. Now the live image is working

**Comment by Lestercity** [comment]
Are you on 10.2 or 10.3? And by "removed", you mean removed the plugin and reinstalled it?

**Comment by LevelOne2k** [comment]
iOS 10.3 Beta 2. 

I mean, I deleted the whole home in the "Home App", and then added again.

**Comment by Lestercity** [comment]
Okay great to hear it is working for you! I am still on 10.2, considering purchase of c2.

**Comment by LevelOne2k** [comment]
Live image only works with WLAN. With Mobil (3G, LTE) the picture remains after a certain time.

**Comment by ersan** [comment]
Hopefully this is changed in iOS 10.3 but I'm not holding my breath - if it isn't do you think you can open an Issue in the foscam-client github to add support for SRTP?  I know it hasn't been updated in a year but I think the developer still reads the issues.

**Comment by marcodesantis71** [comment]
Hi,

Any news for FI9816P on iOS 10.3?

**Comment by BenWoodford** [comment]
Got an FI9816P and no luck either. I'm not even seeing any debug lines when I try to open up the full screen view (not sure if I'm meant to?)

**Comment by Samfox2** [comment]
Does live image work with 10.3 final? I updated yesterday and it`s still not working, only preview mode is ok.

**Comment by MystK** [comment]
I'm on 10.3 and live camera doesn't work for me either.

**Comment by mriksman** [comment]
homebridge-camera-ffmpeg works with the Foscam camera. 

It might be best to separate the motion/security from the camera.

**Comment by theo-69** [comment]
Yes confirm on ffmpeg, could we not integrate it within this plugin?

**Comment by BenWoodford** [comment]
The issue with using ffmpeg is that it does appear to actually do transcoding of the stream. Most people aren't running terribly high spec machines for home automation so it's a pretty poor solution for many of us. I run my HA stuff off a Gigabyte Brix with a Celeron in and using `homebridge-camera-ffmpeg` maxed out the CPU

**Comment by theo-69** [comment]
I am using PI did you try [homebridge-camera-ffmpeg-omx](https://github.com/legotheboss/homebridge-camera-ffmpeg-omx)

however would be great to only use one plugin :(

**Comment by BenWoodford** [comment]
No but I'll give it a go now I know it's a thing!

Having never been able to get the foscam one running - does the Homekit camera integration allow for pan/tilt? Would be nice to have.

**Comment by theo-69** [comment]
@BenWoodford sorry no, and its real slow and bad image...

**Comment by theo-69** [comment]
So sad it seems nobody is developing this plugin anymore, maybe somebody can fork it...

**Comment by theo-69** [comment]
Hi its working in 10.3.3 beta again but the Home App Crashes in 11 beta if you try to see livestream ;-(

**Comment by LevelOne2k** [comment]
Live preview works with iOS 11 Beta 4

**Comment by theo-69** [comment]
IOS 11 no live stream

**Comment by mriksman** [comment]
#52 
This plugin uses 'homebridge-foscam-stream', which does not support SRTP. The best way would probably be to replace the 'handleStreamRequest' and 'prepareStream' (and any dependent code) from 'homebridge-camera-ffmpeg' which has the required SRTP support.

Until a coder carries out this replacement (use 'homebridge-camera-ffmpeg' instead of 'homebridge-foscam-stream' for the video streaming part), then all I can suggest is to use 'homebridge-camera-ffmpeg' for the streaming part. Ignore the camera created by this plugin, or comment out the line that creates the camera service.

For 'homebridge-camera-ffmpeg' ensure to use this source settings;
`"source": "-rtsp_transport tcp -re -i rtsp://`
Using `-rtsp_transport tcp` fixed the constant stop/start (stuttering/pausing) on Raspberry Pi.

**Comment by luisiam** [comment]
#61
