### ISSUE TITLE
Foscam and Quality Live View

### ISSUE THREAD

**Issue by naixra** [luisiam/homebridge-foscamcamera#16]
Hello,

I would like to know if it was possible with the FOSCAM plugin to keep the video quality adjustment as defined with Foscam application (iOS app or web application) (ie HD 720pb 2M or 4M pixel), in Indeed, when I want to view the video with the application home, my setting automatically changes the quality of the stream on "user-defined setting" that is often less clear that the choice "HD mode" or "equilibrium".

Thank you

**Comment by luisiam** [comment]
Actually iOS will pick the resolution based on your connection. In my case, it's always 720p when I am on WiFi and 360p when I am on LTE.

**Comment by naixra** [comment]
Strangely I'm WiFi AC / Ethernet and yet I find the image with the setting defined by iOS less clear that when I choose HD or Equilibrium in the Foscam application. I see it by changing the setting to HD, then when I click on the live preview, the image on my computer with the foscam web application user defined setting and is less clear the picture in HD mode previously selected

**Comment by luisiam** [comment]
Currently the streaming is not working on iOS 10.1. iOS will always change the user defined settings in the foscam application based on the connection. HD and equilibrium settings are not touched. Basically we have no control on the resolution that iOS pick.

**Comment by mriksman** [comment]
Yeah; my missus has iOS 10 and her live stream works. I have iOS 10.1 and I only get the snapshot pictures - no live stream. I hear it is fixed in iOS 10.2?

**Comment by luisiam** [comment]
Currently iOS 10.1 enforced SRTP which was not required in iOS 10. Currently the streaming library is not using SRTP. That's why streaming is not working in iOS 10.1 now. I am not sure why Apple removed the requirement in iOS 10.2 beta.

Refer to #14
