### ISSUE TITLE
Remote Access via Apple TV Gen3

### ISSUE THREAD

**Issue by mriksman** [luisiam/homebridge-foscamcamera#17]
Hi,

Homebridge works great with homebridge-nest and homebridge-wink. However, as soon as I leave my local Wi-Fi, my homebridge-foscamcamera says 'Not Responding'. 

What do I need to do to make this work when I am on 3G/remote?

**Comment by luisiam** [comment]
It has nothing to do with remote access. Currently the problem is that streaming is not supported in iOS 10.1 yet. That's why you are having weird issue now.

Refer to issue #14

**Comment by mriksman** [comment]
But everything to do with Motion Sensor and the Arm/Disarm doesn't work; 
![img_8185](https://cloud.githubusercontent.com/assets/20112339/20034273/74fda82c-a3af-11e6-8457-d8a5f260a0bd.PNG)
The picture shows both as 'No Response'. This has nothing to do with the video streaming part of the plugin right? As soon as I am on 3G I get this. On Wi-Fi, they work fine.
