### ISSUE TITLE
Remote Access via Apple TV Gen 3

### ISSUE THREAD

**Issue by mriksman** [luisiam/homebridge-foscamcamera#18]
This issue is not to do with the live stream. I am aware this is an issue with iOS 10.1.

The Motion Sensor and the Arm/Disarm doesn't work on 3G;  

![img_8185](https://cloud.githubusercontent.com/assets/20112339/20034273/74fda82c-a3af-11e6-8457-d8a5f260a0bd.PNG)

The picture shows both as 'No Response'. This has nothing to do with the video streaming part of the plugin right? As soon as I am on 3G I get this. On Wi-Fi, they work fine.

**Comment by luisiam** [comment]
I have no problem with that but I am using Apple TV 4. I would suggest that you reset your HomeKit and homebridge

**Comment by mriksman** [comment]
Interesting. I wonder if it is related to Apple Gen3 vs Gen4. Your IP address for the foscam is set to a private IP? You don't have any port forwarding or anything right?
I might buy a Gen4 and see if it resolves the issue.
I reset HomeKit and Homebridge when I went to Node 6.6 to install homebridge-foscamcamera.

**Comment by luisiam** [comment]
It's set to private IP since HomeBridge and the camera are in the same network

**Comment by mriksman** [comment]
OK, so the only noticeable difference so far is Gen3 vs Gen4 providing the remote access. 
Will report back once I get the new Apple TV.

**Comment by luisiam** [comment]
Do you have an iPad to try before purchasing a new Apple TV?

**Comment by GrmpfNarf** [comment]
Hi,
maybe it helps:
I have:
Apple TV 3rd Gen
2x Foscam FI9821P V2
1x Foscam FI9804W
Iphone iOS 10.1.1
All cameras just configured with internal ip addresses, no port forwardings etc.

And everything works fine on Wifi and 3G.
The only difference I see the camera model.

Hope it helps a little bit.

**Comment by mriksman** [comment]
After removing the AccessoryInfo and IdentifierCache from The Persist folder, and re-adding the Foscam - I can now access the devices remotely. The static image for the camera doesn't update however.

**Comment by GrmpfNarf** [comment]
Do you mean the Snapshots in the App ?
Thats the same for me. The Snapshots are not updated from remote access. Are they updated via Apple TV 4/ iPad  ?

**Comment by luisiam** [comment]
When the app try to request an update on the snapshot, you will be able to see that from homebridge log. It will be something like "Getting snapshot" and "Got snapshot". If you can see those log but the snapshot is not updateing, it's just remote access is funky. Mine works most of the time but it just takes forever to update most of the time.

**Comment by luisiam** [comment]
One more note, it may depends on the network environment as well. I can always see the log but the snapshots are never updated in the app when I am under my office network. It works fine under cellular network

**Comment by GrmpfNarf** [comment]
Hi,
I've tested this. There is no log entry like "Got Snapshot" or similar. I will Test it via iPad on Monday evening UTC+1.

**Comment by luisiam** [comment]
If you are on local network, do you see the log?

**Comment by GrmpfNarf** [comment]
Hi,
I've tested both 
Local Network same as Camera -> works
Other Local Network -> doesn't work
Celluar -> doesn't work

When it doesn't works there are also no log entries like "Got Snapshot"

**Comment by luisiam** [comment]
So, you will be able to see the log when it works under local network?
That's strange. Other accessories work on remote network as well? I would suggest resetting your iCloud Keychain and resetting your AppleTV.

**Comment by GrmpfNarf** [comment]
Everything works well in Remote networks. Just the snapshots not. 

I can try the reset after Monday.

**Comment by mriksman** [comment]
Confirm the same issue. On home network, I see the log getting snapshot, and the snapshot updates. 
```
[11/27/2016, 12:38:04 PM] [Foscam2] Foscam-NG: Getting snapshot.
[11/27/2016, 12:38:04 PM] [Foscam2] Foscam-NG: Got snapshot.
[11/27/2016, 12:38:15 PM] [Foscam2] Foscam-NG: Getting snapshot.
[11/27/2016, 12:38:15 PM] [Foscam2] Foscam-NG: Got snapshot.
[11/27/2016, 12:38:26 PM] [Foscam2] Foscam-NG: Getting snapshot.
[11/27/2016, 12:38:26 PM] [Foscam2] Foscam-NG: Got snapshot.
```

Off Wi-Fi and on 4G, nothing appears in the log. Motion detection and arm/disarm works.

At the start of this, I was on 4G. Opening and closing the Home app, and moving in and out of the room with the camera, does not cause a snapshot to be logged. When motion is detected, it gets a snapshot, but it doesn't appear in the Home app.

```
[11/27/2016, 12:29:49 PM] [Foscam2] C2 is set to armed (away).
[11/27/2016, 12:30:04 PM] [Foscam2] C2 Motion Detected!
[11/27/2016, 12:30:04 PM] [Foscam2] Foscam-NG: Getting snapshot.
[11/27/2016, 12:30:04 PM] [Foscam2] Foscam-NG: Getting snapshot.
[11/27/2016, 12:30:05 PM] [Foscam2] Foscam-NG: Got snapshot.
[11/27/2016, 12:30:05 PM] [Foscam2] Foscam-NG: Got snapshot.
[11/27/2016, 12:30:05 PM] [Foscam2] Foscam-NG: Getting snapshot.
[11/27/2016, 12:30:05 PM] [Foscam2] Foscam-NG: Got snapshot.
/usr/local/lib/node_modules/homebridge-foscamcamera/index.js:411
    thisCamera.resetMotion = null;
                           ^

TypeError: Cannot set property 'resetMotion' of undefined
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-foscamcamera/index.js:411:28)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
root@beaglebone:~#
```

Unfortunately, it appears Motion Detection is also faulty; and crashes Homebridge... Odd, this was working the other day... I think before I did the latest npm update -g homebridge-foscamcamera.

**Comment by GrmpfNarf** [comment]
The stacktrace crashes the homebridge, same here. It's maybe another issue so it should be reported seperatly.

**Comment by mriksman** [comment]
Yeah #24 and my #25. Will try 0.2.11 later; 
npm update -g homebridge-foscamcamera didn't work, so will try
npm install -g homebridge-foscamcamera later today.

**Comment by mriksman** [comment]
When I turn on my iPad as a Home Hub, it will update the snapshot every 1 minute on 4G, and every 10s on local Wi-Fi. 

When I turn it off, and it reverts back to the Apple TV Gen 3, it will not update on 4G at all.

This is repeatable; turning on and off my iPad as Home Hub essentially enables/disables remote snapshots. Everything else operates normally.

Strange eh?

**Comment by luisiam** [comment]
That actually kind of make sense to me since AppleTV 3 only provide limited support to HomeKit remote. Something like triggers (automation) are not supported with AppleTV 3.

Just did a quick search on the web
https://support.apple.com/en-us/HT207057

*Apple TV (3rd generation) doesn't support remote access to HomeKit-enabled cameras.

**Comment by GrmpfNarf** [comment]
Case closed ;)

**Comment by mriksman** [comment]
Ahhh. Nice. Time to get the missus her new iPad so I can steal her old one.
