### ISSUE TITLE
when the motion sernsor reset the motion status, homebridge will quit abnormally

### ISSUE THREAD

**Issue by zhang8083** [luisiam/homebridge-foscamcamera#24]
the following is the debug info
/usr/local/lib/node_modules/homebridge-foscamcamera/index.js:411
    thisCamera.resetMotion = null;
TypeError: Cannot set property 'resetMotion' of undefined
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-foscamcamera/index.js:411:28)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

**Comment by luisiam** [comment]
Try 0.2.11

**Comment by mriksman** [comment]
npm install -g homebridge-foscamcamera
or
npm update -g homebridge-foscamcamera
?

**Comment by zhang8083** [comment]
@mriksman
npm install -g homebridge-foscamcamera


@luisiam 
great job! thanks a lot!

**Comment by mriksman** [comment]
Brilliant. 0.2.11 fixed that up.
