### ISSUE TITLE
Foscam-Homebridge plugin doesn't work anymore

### ISSUE THREAD

**Issue by naixra** [luisiam/homebridge-foscamcamera#26]
Hello,

I notice Foscam is not recognize in homebridge anymore and I get this message in log :

`(node:24555) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Error: connect EHOSTUNREACH 192.xxx.xxx.xxx:xxxx(myip)`

I just update my ubuntu system, friday it worked but now I don't manage to make it works.

I try to update with this command too without success :

sudo sudo npm install -g homebridge-foscamcamera

Do you have a solution?

Thank you.

**Comment by luisiam** [comment]
Double check your IP. Try to restart your camera as well as your homebridge server

**Comment by naixra** [comment]
Hello,

I checked the IPs. I restarted my camera 2 times. I can connect to my camera via the foscam native application, as well as with my different device locally. I restarted my Homebridge server and the computer that hosts it. But it still does not work.

I deleted Foscam from the Home application, but I can no longer see it in "add accessory".

So I find myself no longer able to use my Foscam camera with Homekit / Home application

Thank you.

**Comment by naixra** [comment]
I deleted the persist folder and reconfigured all accessories and scenes from default again.

Now, everything work again.

It was just annoying that I had to start everything from scratch so suddenly.

Thank you.

**Comment by luisiam** [comment]
If that happens again, just delete the file for the camera in the persist folder only. I may not be necessary to remove everything and reconfigure everything

**Comment by naixra** [comment]
How can I juste delete the camera file? In my persist folder I have four files :

![capture d ecran 2016-12-11 a 22 52 35](https://cloud.githubusercontent.com/assets/1829642/21083621/9705e37e-bff4-11e6-8693-e114b57351c5.png)

and in the first  one I have these lines :

`{"cache":{"f6f986a8-ae40-4f38-aa34-4b232ed91fca|nextIID":11,"f6f986a8-ae40-4f38-aa34-4b232ed91fca|0000003E-0000-1000-8000-0026BB765291|00000014-0000-1000-8000-0026BB765291":2,"f6f986a8-ae40-4f38-aa34-4b232ed91fca|0000003E-0000-1000-8000-0026BB765291|00000020-0000-1000-8000-0026BB765291":3,"f6f986a8-ae40-4f38-aa34-4b232ed91fca|0000003E-0000-1000-8000-0026BB765291|00000021-0000-1000-8000-0026BB765291":4,"f6f986a8-ae40-4f38-aa34-4b232ed91fca|0000003E-0000-1000-8000-0026BB765291|00000023-0000-1000-8000-0026BB765291":5,"f6f986a8-ae40-4f38-aa34-4b232ed91fca|0000003E-0000-1000-8000-0026BB765291|00000030-0000-1000-8000-0026BB765291":6,"f6f986a8-ae40-4f38-aa34-4b232ed91fca|49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE":7,"f6f986a8-ae40-4f38-aa34-4b232ed91fca|49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE|77474A2F-FA98-485E-97BE-4762458774D8":8,"f6f986a8-ae40-4f38-aa34-4b232ed91fca|49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE|FD9FE4CC-D06F-4FFE-96C6-595D464E1026":9,"f6f986a8-ae40-4f38-aa34-4b232ed91fca|49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE|5819A4C2-E1B0-4C9D-B761-3EB1AFF43073":10,"|nextAID":39,"ce47eebc-7fd7-4eb4-ac4e-7b1ef087b35c":2,"ce47eebc-7fd7-4eb4-ac4e-7b1ef087b35c|nextIID":15,xxxxxxx}}`

In second file I have :

`{"cache":{"9f274e2b-4761-4a2e-babd-46aacfb502a0|nextIID":51,"9f274e2b-4761-4a2e-babd-46aacfb502a0|0000003E-0000-1000-8000-0026BB765291|00000014-0000-1000-8000-0026BB765291":2,"9f274e2b-4761-4a2e-babd-46aacfb502a0|0000003E-0000-1000-8000-0026BB765291|00000020-0000-1000-8000-0026BB765291":3,"9f274e2b-4761-4a2e-babd-46aacfb502a0|0000003E-0000-1000-8000-0026BB765291|00000021-0000-1000-8000-0026BB765291":4,"9f274e2b-4761-4a2e-babd-46aacfb502a0|0000003E-0000-1000-8000-0026BB765291|00000023-0000-1000-8000-0026BB765291":5,"9f274e2b-4761-4a2e-babd-46aacfb502a0|0000003E-0000-1000-8000-0026BB765291|00000030-0000-1000-8000-0026BB765291":6,"9f274e2b-4761-4a2e-babd-46aacfb502a0|0000003E-0000-1000-8000-0026BB765291|00000052-0000-1000-8000-0026BB765291":49,"9f274e2b-4761-4a2e-babd-46aacfb502a0|0000003E-0000-1000-8000-0026BB765291|00000053-0000-1000-8000-0026BB765291":50,"9f274e2b-4761-4a2e-babd-46aacfb502a0|00000110-0000-1000-8000-0026BB765291|0":7,"9f274e2b-4761-4a2e-babd-46aacfb502a0|00000110-0000-1000-8000-0026BB765291|0|00000114-0000-1000-8000-0026BB765291":8,"9f274e2b-4761-4a2e-babd-46aacfb502a0|00000110-0000-1000-8000-0026BB765291|0|00000115-0000-1000-8000-0026BB765291":9,"9f274e2b-4761-4a2e-babd-46aacfb502a0|00000110-0000-1000-8000-0026BB765291|0|00000116-0000-1000-8000-0026BB765291":10,"9f274e2b-4761-4a2e-babd-46aacfb502a0|00000110-0000-1000-8000-0026BB765291|0|00000117-0000-1000-8000-0026BB765291":11,"9f274e2b-4761-4a2e-babd-46aacfb502a0|00000110-0000-1000-8000-0026BB765291|0|00000120-0000-1000-8000-0026BB765291":12,xxxx}`

in third file I have :

`{"displayName":"Homebridge","category":2,"pincode":"031-45-154","signSk":"xxxxxx":"xxxxxxx":"xxxxxxx"},"configVersion":4,"configHash":"xxxxxxx","relayEnabled":false,"relayState":2,"relayAccessoryID":"","relayAdminID":"","relayPairedControllers":{},"accessoryBagURL":""}`

and in last file I have :

`{"displayName":"Foscam R2","category":17,"pincode":"031-45-154","signSk":"xxxxx","signPk":"xxxxx","pairedClients":{"xxxxx":"xxxxx":"xxxxxx"},"configVersion":2,"configHash":"xxxxxx","relayEnabled":false,"relayState":2,"relayAccessoryID":"","relayAdminID":"","relayPairedControllers":{},"accessoryBagURL":""}`

How can I identify camera line to delete it? I don't know how can I just delete camera file it why I delete all of them... and I have to reconfigure everything from nothing.

If I delete the last file where foscam appear, does it work? Do I delete anything else?

Thank you.

**Comment by luisiam** [comment]
Just remove `AccessoryInfo.9086636269AD.json` and `IdentifierCache.9086636269AD.json`. Those 2 files correspond to your camera settings. The other 2 files correspond to the main Homebridge settings.
