### ISSUE TITLE
Explanation for the alarm states

### ISSUE THREAD

**Issue by nitaybz** [luisiam/homebridge-foscamcamera#29]
I don't get this explanation:

> The supported configurations depend on your device. The Foscam public CGI defines the following:
> bit 3 | bit 2 | bit 1 | bit 0
> bit 0 = Ring
> bit 1 = Send email
> bit 2 = Snap picture
> bit 3 = Record
> 
> The following seems to be valid for the C2 as well (not found in any documentation)
> bit 7 | bit 6 | bit 5 | bit 4 | bit 3 | bit 2 | bit 1 | bit 0
> bit 0 = Ring
> bit 1 = Send email
> bit 2 = Snap picture
> bit 3 = Record
> bit 7 = Push notification
> 
> Note: The configuration is defined as int, thus the followings are valid, e.g. 0 (Do Nothing), 1 (Ring), 2 (Email), 3 (Ring + Email), 4 (Record), 12 (Picture and Record), 13 (Ring, Picture and Record), etc.

Can someone help me please to find out what is the right number to use in each state?
first of all I want to realize what does "Ring" mean?
Also I couldn't figured out what are the numbers 14 and 15 (that can be seen in the config.sample), what do they represent? how do i choose bit7 (push notification) in this configuration? for how long does the record actually record?

Where do I find more information about it?

By the way, I'm using R2 camera

Thanks!

**Comment by luisiam** [comment]
You can find more more information here:
https://github.com/lightswitch05/foscam-client/blob/master/HD%20cameras%20SDK%20CGI%20(1)/Foscam%20IPCamera%20CGI%20User%20Guide-3518%20Ver.1.0.10.pdf

**Comment by nitaybz** [comment]
Ok I think I figured out what's going on here and what are bits....
I'm just curious to know, if bit2 is picture and bit3 is record, how come using the value 4 will be "Record"? isn't 4 stand for bit2(which is for picture)?

**Comment by luisiam** [comment]
It's in binary. 4 means 100 in binary and only bit3 is set to 1. Therefore, it's record only.

**Comment by nitaybz** [comment]
Thanks for the answer, I tried to look for it from this resource:
http://l3d.cs.colorado.edu/courses/CSCI1200-96/binary.html
seems like 1000 means 8, did you mean 0100 ?

**Comment by luisiam** [comment]
Oh yes, that's a typo. You are right

**Comment by nitaybz** [comment]
so if the 1 is on bit3 what is bit0?

**Comment by luisiam** [comment]
It's a decimal/binary conversion. You specify which bit is 1
http://www.binaryhexconverter.com/binary-to-decimal-converter

**Comment by nitaybz** [comment]
still... thats not helping...
I think there is some mistake, as far as I learned now:
bit0: 0001 = 1
bit1: 0010 = 2
bit2: 0100 = 4
bit3: 1000 = 8
it's always 2  power of (bit?)
and so on..
that is what I understand - therefor 4= bit 2 = picture. 
correct me where I'm wrong

**Comment by luisiam** [comment]
Yes, you are right. What's you concern? What do you want to set on each state? I can do the calculation for you.

**Comment by nitaybz** [comment]
I need to set up one state for record and the other for picture.
I think it should be 8 for Record(bit3=8) and 4 for snap picture(bit2=4) and not like mentioned in the read.md.
do you think otherwise?

**Comment by luisiam** [comment]
Thanks for pointing it out. Never notice there's typo in the readme.

**Comment by nitaybz** [comment]
oh thanks! I got so confused from it... I found this nice table that shows the bits and their values:

![image](https://cloud.githubusercontent.com/assets/16838394/22130986/91595aea-deb8-11e6-94c5-c3a0dede98e3.png)

**Comment by nitaybz** [comment]
everything is clear now and I got a pretty nice lesson
