### ISSUE TITLE
Streaming Error

### ISSUE THREAD

**Issue by abataille** [luisiam/homebridge-foscamcamera#3]
After some time, I detected the following error that caused home bridge to crash.

(node:5438) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 254): Error: This socket has been ended by the other party
Sat, 01 Oct 2016 14:28:33 GMT Accessory [Homebridge RPi3] Got Characteristic "On" value: false
Sat, 01 Oct 2016 14:28:33 GMT EventedHTTPServer [::ffff:192.168.178.29] HTTP Response is finished
Sat, 01 Oct 2016 14:28:34 GMT EventedHTTPServer [::ffff:192.168.178.53] HTTP request: /characteristics
Sat, 01 Oct 2016 14:28:34 GMT HAPServer [E2:CD:13:7C:9E:FA] HAP Request: PUT /characteristics
Sat, 01 Oct 2016 14:28:34 GMT Accessory [Foscam Wohnzimmer] Processing characteristic set: [{"aid":1,"iid":15,"value":"ARDA7NKIyypGvZ2EavNCCg3+AxsBAQACDjE5Mi4xNjguMTc4LjUzAwLF1gQCP/4EBwIAAwABAQIFBwIAAwABAQI="}]
Sat, 01 Oct 2016 14:28:34 GMT Accessory [Foscam Wohnzimmer] Setting Characteristic "Setup Endpoints" to value ARDA7NKIyypGvZ2EavNCCg3+AxsBAQACDjE5Mi4xNjguMTc4LjUzAwLF1gQCP/4EBwIAAwABAQIFBwIAAwABAQI=
Sat, 01 Oct 2016 14:28:34 GMT StreamController 
Session:  <Buffer@0x2ea5f8a c0 ec d2 88 cb 2a 46 bd 9d 84 6a f3 42 0a 0d fe> 
ControllerAddress:  192.168.178.53 
VideoPort:  54981 
AudioPort:  65087 
Video Crypto:  2 
Video Master Key:  <Buffer@0x2ea5fbb > 
Video Master Salt:  <Buffer@0x2ea5fbd > 
Audio Crypto:  2 
Audio Master Key:  <Buffer@0x2ea5fc4 > 
Audio Master Salt:  <Buffer@0x2ea5fc6 >
Sat, 01 Oct 2016 14:28:35 GMT rtsp-stream start-line sent SETUP rtsp://192.168.178.21:88/videoMain/track1 RTSP/1.0
Sat, 01 Oct 2016 14:28:35 GMT rtsp-stream headers sent { Transport: 'RTP/AVP;unicast;client_port=10000-10001',
  CSeq: 16,
  Authorization: 'Digest username="RV", realm="Foscam IPCam Living Video", nonce="771d46cf7a832a3d0aeb0d41065e5765", uri="rtsp://192.168.178.21:88/videoMain/track1", response="2393ad66fd88f5c8415955eb2453e448",' }
(node:5438) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 255): Error: This socket has been ended by the other party
buffer.js:1021
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkInt (buffer.js:1021:11)
    at Buffer.writeUInt32BE (buffer.js:1112:5)
    at RTPProxy.rtpMessage (/usr/lib/node_modules/hap-nodejs/lib/camera/RTPProxy.js:142:9)
    at Socket.<anonymous> (/usr/lib/node_modules/hap-nodejs/lib/camera/RTPProxy.js:118:14)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)

**Comment by luisiam** [comment]
Which model of Camera are you using? Does that happen all the time? Try to update to the latest firmware. 

Per @planetbeing, this happens when the streaming data is broken. At this point we cannot do anything since HAP-NodeJS crashes homebridge when it receives broken data.

**Comment by abataille** [comment]
Model is FI9821W v2 with the latest firmware.
What will happen, if i.e. the wlan connection to the camera breaks during the stream?
It runs stable over the last couple of hours.

**Comment by luisiam** [comment]
I believe it's fine if you are not streaming at the same time or else it will crash. Don't quote me on this though. However, don't you have homebridge set up to recover from crash?

Regards,
Luis Iam.

On Sat, Oct 1, 2016 at 1:34 PM -0700, "abataille" notifications@github.com wrote:

Model is FI9821W v2 with the latest firmware.

What will happen, if i.e. the wlan connection to the camera breaks during the stream?

It runs stable over the last couple of hours.

**Comment by abataille** [comment]
What is the correct way to recover from crash? Any link?

**Comment by luisiam** [comment]
I set up homebridge with the following guide so my homebridge can recover from crash
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd

There are a lot other method, too. Such as 'forever'

**Comment by luisiam** [comment]
Update homebridge and this plugin to latest version should be able to fix this issue
