### ISSUE TITLE
Use without Motion Sensor Security System possible?

### ISSUE THREAD

**Issue by FaceMan4** [luisiam/homebridge-foscamcamera#37]
Hi,
is there a way to use only the Camera and don`t include the Security System and Motion items in the Home App?
I'am using a Homekit Hardware Motion Sensor, thats why i aksing.
Thanks.

**Comment by luisiam** [comment]
Currently it's not possible. All the services are deeply integrated with each other already. Without the security system implementation, you will not be able to activate/deactivate motion detection of the camera via the HomeKit app. If you are only looking into a camera implementation, you can checkout 
https://github.com/planetbeing/homebridge-foscam-ng

**Comment by FaceMan4** [comment]
Thank you!
