### ISSUE TITLE
Is Streaming Working?

### ISSUE THREAD

**Issue by mriksman** [luisiam/homebridge-foscamcamera#40]
Hi, I first installed this plugin in iOS 10 - so I have never seen streaming working. I'm on iOS 10.3, and I still get 'No Response. This camera is not responding' when I click and open the camera up. Snapshots work and update every 10 seconds. I have a Foscam C2.

Should this be working? Or is it still an issue? Or have I got something wrong with my Beaglebone/Debian.

**Comment by luisiam** [comment]
Please read the ReadMe file and refer to issue #14 
ReadMe: `https://github.com/luisiam/homebridge-foscamcamera#important-notice`

**Comment by mriksman** [comment]
I've been following that; some people said they had it working on 10.3?

**Comment by mriksman** [comment]
I tried homebridge-camera-ffmpeg by KhaosT and that works with the Foscam C2 camera.
