### ISSUE TITLE
No Live Stream on FI9800P

### ISSUE THREAD

**Issue by nitaybz** [luisiam/homebridge-foscamcamera#41]
Hi Guys, I need your help.
I have 2 Foscam cameras, one is R2 (V2) that works perfectly with this plugin, I can watch live stream even on 3G connection.

the problem I have is with my new Foscam FI9800P camera, the camera is recognized and I can get snapshots, I just can't get a live stream on Home app.

I noticed 2 things that might help you understand.

For the R2 camera I can see that the connection is using the port from the config file (88), Example: rtsp://username:password@10.0.0.XX:88/videoMain
but for the FI9800P camera it seems like it's not using the port from the config file which is set to 89, instead it's using port 554 which I noticed related to the RTSP setup in the Foscam settings.
Example: rtsp://username:password@10.0.0.XX:554/videoMain

another thing is that I see some kind of an error in the logs:
```
Apr 25 18:30:57 raspberrypi homebridge[10725]: (node:10725) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: self.transcoderClass is not a constructor
Apr 25 18:31:07 raspberrypi homebridge[10725]: [4/25/2017, 6:31:07 PM] [Living Room Foscam] Stop: rtsp://username:password@10.0.0.**:554/videoMain
```

I'm using iPhone 7 with both iPad and AppleTV 4 as hubs, all of them are using the latest betas.

Please help me get the live stream!
Thanks

**Comment by luisiam** [comment]
Please read the ReadMe file and refer to issue #14 
ReadMe: `https://github.com/luisiam/homebridge-foscamcamera#important-notice`

**Comment by nitaybz** [comment]
yes but on iOS 10.3 my R2 is working with live stream... how can you explain that?
