### ISSUE TITLE
How to configure "away", "stay" and "night"

### ISSUE THREAD

**Issue by Rubenfer** [luisiam/homebridge-foscamcamera#44]
I don't know which values set on labels "away", "stay" and "night". The documentation of the plugin say:

> The support configuration depends on your device. The foscam public cgi defines the following:
> 
> bit 3 | bit 2 | bit 1 | bit 0
> 
> bit 0 = Ring bit 1 = Send email bit 2 = Snap picture bit 3 = Record
> 
> Note: The configuration is defined as int, thus the following are valid, for example: 0 (Do Nothing), 1 (Ring), 2 (Email), 3 (Ring + Email), 4 (Record), 12 (Picture and Record), 13 (Ring, Picture and Record), etc.

But I don't understand why 13 is Ring, Picture and Record; and why 3 is Ring+Email,... Anyone can say me how to create this values? I need the value for Email+Picture+Record and the value for Picture+Record.

An other question is: "Picture" is for iOS Notification or for save the screenshot on the SD card of Foscam camera?

Thanks!!

**Comment by luisiam** [comment]
It is in binary
Email+Picture+Record = 14
Picture+Record = 12

Picture is for saving the screenshot to the SD card.

**Comment by theo-69** [comment]
would like to have a more specific explanation as well please...

**Comment by Rubenfer** [comment]
@luisiam Thank you, I understand. 

@theo-69 very easy, you get the binary number with true or false value (1 or 0) and you convert it to hexadecimal. 

The binary code is: (Ring)(Send email)(Snap picture)(Record). If you want only ring is 1000 to hexadecimal. If you want only Record is 0001 to hexadecimal, if you want ring + record is 1001 to hexadecimal,...
