### ISSUE TITLE
iOS11 Can't Add Cameras as Accessories

### ISSUE THREAD

**Issue by LumpyPoopie** [luisiam/homebridge-foscamcamera#51]
In iOS10, each camera could be added to HomeKit as separate accessories with the same pin as when Homebridge was added.  However, in iOS11, the cameras don't appear as accessories to add.  Homebridge may be added, but pairing with each camera separately cannot be done as the instructions state:

"Due to protocol limitation, users will need to pair with the camera in a HomeKit app separately.
Pairing PIN is the same as the HomeBridge pairing PIN."

How are cameras added to Homebridge in iOS11?

**Comment by theo-69** [comment]
same than before

**Comment by LumpyPoopie** [comment]
I figured out why it wouldn't load.  I had previously added it in iOS 10 and deleted it for a fresh install to HomeKit.  The persist directory retained the camera information in it, and prevented the cameras from appearing as new accessories.  After deleting the persist directory, I was able to add the cameras.
