### ISSUE TITLE
Failed to retrieve camera information!

### ISSUE THREAD

**Issue by barryl93** [luisiam/homebridge-foscamcamera#62]
Hi! I just installed the plugin for the first time and I don't see my camera in the Home app. The only glitch I can see is "Failed to retrieve camera information!" during Homebridge loading in Terminal.

Here's the relevant config info...

 {
            "platform": "FoscamCamera",
            "name": "Foscam",
            "cameras": [
                {
                    "name": "Birdies",
                    "password": "XXXXXXXXX",
                    "host": "192.168.1.###",
                    "port": 88
                }
            ]
        }

I'm sure I'm missing something incredibly obvious, but I can't see it...

Any help would be greatly appreciated!

**Comment by toshibochan** [comment]
look the main page have config example! you missing username and password and other things!!!!!!

**Comment by toshibochan** [comment]
"platforms": [{
    "platform": "FoscamCamera",
    "name": "Foscam",
    "cameras": [{
        "username": "admin",
        "password": "password",
        "host": "192.168.1.10",
        "port": 88,
        "stay": 13,
        "away": 15,
        "night": 14

**Comment by barryl93** [comment]
Hi! Thanks for your input. But you'll see that I do, in fact, have my password in there: I just replaced it with X's for posting purposes.

As to username: According to the docs, that's an optional field, so I left it off.

**Comment by barryl93** [comment]
After a whole of trial and error, I was able to eliminate this issue! (Tried a different port for rtsp and the problem went away!) So, closing this down.
