### ISSUE TITLE
Camera model support?

### ISSUE THREAD

**Issue by rbyrbt** [luisiam/homebridge-foscamcamera#7]
I've got older Foscam FI8910W (MJPEG) cameras - are these supported? If not which models are supported?

Receiving the following error on home bridge launch.

```
(node:13071) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 404 - <HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD>
<BODY BGCOLOR="#cc9999"><H4>404 Not Found</H4>
File not found.
</BODY></HTML>
```

**Comment by toshibochan** [comment]
My FI8910W no work. FI19821W V2 and FI19831W is working for me

**Comment by luisiam** [comment]
This plugin is developed based on H.264 HD camera. You may try with MJPEG one but I cannot provide any support on that.

**Comment by rbyrbt** [comment]
Thanks for the confirmation and clarification. I'll upgrade to an H.264 camera thanks.

**Comment by rbyrbt** [comment]
Has anyone had success with the Foscam R2?

**Comment by luisiam** [comment]
I remember one user is using C2 without problem. I don't think there's much differences between C2 and R2 except PTZ

**Comment by rbyrbt** [comment]
Following up, just received a Foscam R2 and added it to homebridge-foscamcamera 0.1.16 without issue. I'm new to cameras in HomeKit/Homebridge, but is camera movement control supported?

**Comment by luisiam** [comment]
PTZ is not supported at the moment
