### ISSUE TITLE
Streaming error

### ISSUE THREAD

**Issue by abataille** [luisiam/homebridge-foscamcamera#8]
After successfully having it run over a couple of day, today it crashed with the following error:

...
Thu, 13 Oct 2016 07:36:22 GMT StreamController 
Session:  <Buffer@0x1efbeaa 0d 0d da 8a 73 69 4b 96 a7 1f f9 46 61 62 09 50> 
ControllerAddress:  192.168.178.53 
VideoPort:  64154 
AudioPort:  52448 
Video Crypto:  2 
Video Master Key:  <Buffer@0x1efbedb > 
Video Master Salt:  <Buffer@0x1efbedd > 
Audio Crypto:  2 
Audio Master Key:  <Buffer@0x1efbee4 > 
Audio Master Salt:  <Buffer@0x1efbee6 >
Thu, 13 Oct 2016 07:36:22 GMT rtsp-stream start-line sent SETUP rtsp://192.168.178.21:88/videoMain/track1 RTSP/1.0
Thu, 13 Oct 2016 07:36:22 GMT rtsp-stream headers sent { Transport: 'RTP/AVP;unicast;client_port=10000-10001',
  CSeq: 3,
  Authorization: 'Digest username="RV", realm="Foscam IPCam Living Video", nonce="564ee45d32c0933144238e5e8ee1161f", uri="rtsp://192.168.178.21:88/videoMain/track1", response="13748afdd8dd7099ae00d00b8f4a8cb8",' }
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream decoding chunk 'RTSP/1.0 200 OK\r\nCSeq: 3\r\nDate: Thu, Oct 13 2016 07:36:31 GMT\r\nTransport: RTP/AVP;unicast;destination=192.168.178.55;source=192.168.178.21;client_port=10000-10001;server_port=6970-6971\r\nSession: 660EFFB5;timeout=65\r\n\r\n'
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream start of header
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream end of header
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream start-line sent SETUP rtsp://192.168.178.21:88/videoMain/track2 RTSP/1.0
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream headers sent { Transport: 'RTP/AVP;unicast;client_port=10006-10007',
  CSeq: 4,
  Authorization: 'Digest username="RV", realm="Foscam IPCam Living Video", nonce="564ee45d32c0933144238e5e8ee1161f", uri="rtsp://192.168.178.21:88/videoMain/track2", response="8dae190336204dffaa44b6bfde7d6323",',
  Session: '660EFFB5' }
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream decoding chunk 'RTSP/1.0 200 OK\r\nCSeq: 4\r\nDate: Thu, Oct 13 2016 07:36:32 GMT\r\nTransport: RTP/AVP;unicast;destination=192.168.178.55;source=192.168.178.21;client_port=10006-10007;server_port=6972-6973\r\nSession: 660EFFB5;timeout=65\r\n\r\n'
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream start of header
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream end of header
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.29] Sending HTTP event '1.22' with data: {"characteristics":[{"aid":1,"iid":22,"value":"ARANDdqKc2lLlqcf+UZhYglQAxsBAQACDjE5Mi4xNjguMTc4LjUzAwKa+gQC4MwEBwIAAwABAQIFBwIAAwABAQI="}]}
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] Muting event '1.22' notification for this connection since it originated here.
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.29] Sending HTTP event '1.22' with data: {"characteristics":[{"aid":1,"iid":22,"value":"ARANDdqKc2lLlqcf+UZhYglQAxsBAQACDjE5Mi4xNjguMTc4LjUzAwKa+gQC4MwEBwIAAwABAQIFBwIAAwABAQI="}]}
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] Muting event '1.22' notification for this connection since it originated here.
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] HTTP Response is finished
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] HTTP request: /characteristics?id=1.22
Thu, 13 Oct 2016 07:36:23 GMT HAPServer [E2:CD:13:7C:9E:FA] HAP Request: GET /characteristics?id=1.22
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Getting value for Characteristic "Setup Endpoints"
Thu, 13 Oct 2016 07:36:23 GMT StreamController Setup Read
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Got Characteristic "Setup Endpoints" value: ARANDdqKc2lLlqcf+UZhYglQAgEAAxsBAQACDjE5Mi4xNjguMTc4LjU1AwISJwQCGCcEBwEBAgIAAwAFBwEBAgIAAwAGBAc74cwHBKJZqy8=
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.29] Sending HTTP event '1.22' with data: {"characteristics":[{"aid":1,"iid":22,"value":"ARANDdqKc2lLlqcf+UZhYglQAgEAAxsBAQACDjE5Mi4xNjguMTc4LjU1AwISJwQCGCcEBwEBAgIAAwAFBwEBAgIAAwAGBAc74cwHBKJZqy8="}]}
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] Muting event '1.22' notification for this connection since it originated here.
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.29] Sending HTTP event '1.22' with data: {"characteristics":[{"aid":1,"iid":22,"value":"ARANDdqKc2lLlqcf+UZhYglQAgEAAxsBAQACDjE5Mi4xNjguMTc4LjU1AwISJwQCGCcEBwEBAgIAAwAFBwEBAgIAAwAGBAc74cwHBKJZqy8="}]}
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] Muting event '1.22' notification for this connection since it originated here.
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] HTTP Response is finished
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] HTTP request: /characteristics
Thu, 13 Oct 2016 07:36:23 GMT HAPServer [E2:CD:13:7C:9E:FA] HAP Request: PUT /characteristics
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Processing characteristic set: [{"aid":1,"iid":20,"value":"ARUCAQABEA0N2opzaUuWpx/5RmFiCVA="}]
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Setting Characteristic "Selected Stream Configuration" to value ARUCAQABEA0N2opzaUuWpx/5RmFiCVA=
Thu, 13 Oct 2016 07:36:23 GMT StreamController Write SelectedStreamConfiguration
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream start-line sent TEARDOWN rtsp://192.168.178.21:88/videoMain RTSP/1.0
Thu, 13 Oct 2016 07:36:23 GMT rtsp-stream headers sent { Session: '660EFFB5',
  CSeq: 5,
  Authorization: 'Digest username="RV", realm="Foscam IPCam Living Video", nonce="564ee45d32c0933144238e5e8ee1161f", uri="rtsp://192.168.178.21:88/videoMain", response="9cc4c22e78ea81ae74f8118163e0bf40",' }
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] HTTP Response is finished
Thu, 13 Oct 2016 07:36:23 GMT EventedHTTPServer [::ffff:192.168.178.53] HTTP request: /characteristics
Thu, 13 Oct 2016 07:36:23 GMT HAPServer [E2:CD:13:7C:9E:FA] HAP Request: PUT /characteristics
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Processing characteristic set: [{"aid":1,"iid":20,"value":null}]
Thu, 13 Oct 2016 07:36:23 GMT Accessory [Foscam Cam2] Setting Characteristic "Selected Stream Configuration" to value null
Thu, 13 Oct 2016 07:36:23 GMT StreamController Write SelectedStreamConfiguration
buffer.js:257
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:257:9)
    at Function.Buffer.from (buffer.js:97:10)
    at Buffer (buffer.js:76:17)
    at StreamController._handleSelectedStreamConfigurationWrite (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:280:14)
    at .<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:261:12)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
    at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
    at Accessory.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:727:22)
    at Array.forEach (native)
    at Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:672:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:966:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:203:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Any idea.
Second, the plugin is somehow chatty. Is there a way to reduce the messages into the error .log ?

**Comment by luisiam** [comment]
This error should be reported to `HAP-NodeJS`

The log is important for debugging purposes when something goes wrong. Streaming is a lot more complicated and there's a lot of handshaking going on.

**Comment by abataille** [comment]
I posted the issue at HAP-NodeJS
