### ISSUE TITLE
Failed to retrieve current state!

### ISSUE THREAD

**Issue by rbyrbt** [luisiam/homebridge-foscamcamera#9]
Retrieving the current state on the last camera only - all Foscam R2. Modifying the config (sort order/removing entries) appears to support this. Any ideas?

Homebridge 0.4.6
Node v6.7.0
foscamcamera 0.1.16

---

{
    "bridge": {
        "name": "homebridge",
        "username": "AA:AA:AA:AA:AA:AA",
        "port": 51000,
        "pin": "123-45-678"
    },

```
"description": "Test",

"accessories": [],
```

"platforms": [{
    "platform": "FoscamCamera",
    "cameras": [{
        "username": "User1",
        "password": "Password1",
        "host": "10.0.1.101",
        "port": 8581,
        "stay": 0,
        "away": 14,
        "night": 4
    }, {
        "username": "User2",
        "password": "Password2",
        "host": "10.0.1.102",
        "port": 8581,
        "stay": 12,
        "away": 14,
        "night": 12
    }, {
        "username": "User3",
        "password": "Password3",
        "host": "10.0.1.103",
        "port": 8581,
        "stay": 12,
        "away": 14,
        "night": 12
    }]
}]

}

**Comment by lijamez** [comment]
I encountered this issue when setting up more than 1 camera with different credentials. The root cause of this bug was in a dependency, foscam-client. I have fixed this a few hours ago but I'm not sure when it'll be in available in npm. 
https://github.com/lightswitch05/foscam-client/pull/16

**Comment by rbyrbt** [comment]
Yeah I was just thinking the multiple credentials too! Do I need consistent admin credentials, or can I make a shared "visitor" or "operator" user across all cameras?

Thanks!

**Comment by lijamez** [comment]
I just tested it and found that visitor and operator accounts won't work. You'll get a "Failed to retrieve camera information!" error. If you really want to get it working now, you can try to change your admin credentials to be the same across all cameras. Otherwise, just wait for @luisiam to update homebridge-foscamcamera to use the latest foscam-client (which is 0.4.0).

**Comment by rbyrbt** [comment]
Awesome - thanks. Keep up the great work!

**Comment by toshibochan** [comment]
You have all the cameras at same port?

**Comment by luisiam** [comment]
Thanks @lijamez for fixing this issue. I have already updated the dependency. However, the library for the streaming portion, homebridge-foscam-stream, is still not updated. We will need to wait for @planetbeing to push an update for that. In the meantime, streaming may not work on your setup.

**Comment by rbyrbt** [comment]
Just updated to 0.1.17 - to confirm, no more issue with retrieving state with multiple admin credentials. @toshibochan I had all cameras on the same port while testing, but all cameras are on different ports now. 
Thanks all!
